<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container  h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10 text-dark">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">

                                <div class="text-center">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp" style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-3 pb-1">We are The Cedcoss Team</h4>
                                </div>

                                <form action="login/login" method="post">
                                    <p>Please login to your account</p>

                                    <div class="form-outline mb-2">
                                        <input type="email" id="form2Example11" class="form-control" placeholder="email address" value="<?php echo $this->session->get('email') ?>" name="email" />
                                        <label class="form-label" for="form2Example11">Username</label>
                                    </div>

                                    <div class="form-outline mb-2">
                                        <input type="password" id="form2Example22" class="form-control" value="<?php echo $this->session->get('pswd') ?>" name="pswd" />
                                        <label class="form-label" for="form2Example22">Password</label>
                                    </div>

                                    <div class="text-center pt-1 mb-3 pb-1">
                                        <input class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">
                                        </input>

                                    </div>

                                    <div class="d-flex align-items-center justify-content-center pb-2">
                                        <p class="mb-0 me-2">Don't have an account?</p>
                                        <a href="signup">Create New Account</a>
                                    </div>

                                </form>

                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-center gradient-custom-2 bg-#d33a7d">
                            <div class="text-primary px-3 py-4 p-md-5 mx-md-4">
                                <h4 class="mb-2">We are more than just a company</h4>
                                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>