<?php
session_start();
foreach ($_SESSION['data'] as $key1 => $value1) {
    echo "<h1 class='text-center m-3'>
    <span  class=' text-primary bg-white display-4  p-2' style='border-radius:15px'> $key1</span></h1>";
    echo "<div class='row '>";
    foreach ($value1['items'] as $key => $value) {
        if (empty($value['images'])) {
            $img = 'https://i.scdn.co/image/ab6761610000e5eb8de0e6e7e55d7773931ab7f4';
        } else {
            $img = $value['images'][0]['url'];
        }
        if ($key1 == 'tracks') {
            $img = $value['album']['images'][0]['url'];
        }
        echo "<div class='card col-3 p-3 border  border-5 border-white bg-dark text-light mb-1'
             style='width: 18rem;height:330px;border-radius:10px; '>
    <img class='card-img-top' src=' " . $img . " ' alt='Card image cap' height=180px>
    <div class='card-body'>
      <h6 class='card-title'>$value[name]</h6>
      <a href='add?spotifyid=$value[id]&type=$value[type]' class='btn btn-primary border border-white'>Add $key1</a>
    </div>
  </div>
  ";
    }
    echo "</div>";
}
